M48
; DRILL file {KiCad 8.0.5} date 2024-12-11T15:25:16-0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-12-11T15:25:16-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1378
%
G90
G05
T1
X4.8031Y-2.9528
X4.8031Y-4.5276
X6.9685Y-2.9528
X6.9685Y-4.5276
M30
